import img1 from "@/assets/image/Frame 45814.png";
import img2 from "@/assets/image/Frame 45815.png";
import img3 from "@/assets/image/Frame 45816.png";
import img4 from "@/assets/image/Frame 45817.png";
import img5 from "@/assets/image/Frame 45818.png";
import img6 from "@/assets/image/Frame 45819.png";
import img7 from "@/assets/image/Frame 45820.png";
import product1 from "@/assets/image/product1.png";
import product2 from "@/assets/image/product2.png";
import product3 from "@/assets/image/product3.png";
import product4 from "@/assets/image/product4.png";
import avatar from "@/assets/icons/macbro.svg";
import korzinkaLogo from "@/assets/icons/korzinkaLogo.svg";
import makroLogo from "@/assets/icons/makroLogo.svg";
import samsungLogo from "@/assets/icons/samsungLogo.svg";
import terraProLogo from "@/assets/icons/terraProLogo.svg";
import smartLogo from "@/assets/icons/smartLogo.svg";
import type { ICategory, IProduct } from "@/types";

export const category: ICategory[] = [
  {
    id: 1,
    title: "electronics",
    img: img1,
  },
  {
    id: 2,
    title: "books",
    img: img2,
  },
  {
    id: 3,
    title: "HouseholdAppliances",
    img: img3,
  },
  {
    id: 4,
    title: "furniture",
    img: img4,
  },
  {
    id: 5,
    title: "homeGarden",
    img: img5,
  },
  {
    id: 6,
    title: "childrensGoods",
    img: img6,
  },
  {
    id: 7,
    title: "clothes",
    img: img7,
  },
  {
    id: 8,
    title: "electronics",
    img: img1,
  },
  {
    id: 9,
    title: "books",
    img: img2,
  },
  {
    id: 10,
    title: "HouseholdAppliances",
    img: img3,
  },
  {
    id: 11,
    title: "furniture",
    img: img4,
  },
  {
    id: 12,
    title: "homeGarden",
    img: img5,
  },
  {
    id: 13,
    title: "childrensGoods",
    img: img6,
  },
  {
    id: 14,
    title: "clothes",
    img: img7,
  },
];

export const partners = [
  korzinkaLogo,
  makroLogo,
  smartLogo,
  terraProLogo,
  samsungLogo,
  makroLogo,
];

export const productsForBestAds: IProduct[] = [
  {
    id: "best1",
    productTitle: "product1",
    img: product1,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "slot",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "best2",
    productTitle: "product2",
    img: product2,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "best3",
    productTitle: "product3",
    img: product3,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "slot",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "best4",
    productTitle: "product4",
    img: product4,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
];
export const productsForDiscountNearby: IProduct[] = [
  {
    id: "discountNearby1",
    productTitle: "product1",
    img: product1,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "discountNearby2",
    productTitle: "product2",
    img: product2,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "discountNearby3",
    productTitle: "product3",
    img: product3,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "discountNearby4",
    productTitle: "product4",
    img: product4,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
];
export const productsForDiscountStartAnnouncement: IProduct[] = [
  {
    id: "discountStart1",
    productTitle: "product1",
    img: product1,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "discountStart2",
    productTitle: "product2",
    img: product2,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "discountStart3",
    productTitle: "product3",
    img: product3,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "discountStart4",
    productTitle: "product4",
    img: product4,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
];
export const productsForLastViewedAds: IProduct[] = [
  {
    id: "lastViewed1",
    productTitle: "product1",
    img: product1,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "lastViewed2",
    productTitle: "product2",
    img: product2,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "lastViewed3",
    productTitle: "product3",
    img: product3,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "lastViewed4",
    productTitle: "product4",
    img: product4,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
];
export const productsForStoppedAds: IProduct[] = [
  {
    id: "stoppedAds1",
    productTitle: "product1",
    img: product1,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "stoppedAds2",
    productTitle: "product2",
    img: product2,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "stoppedAds3",
    productTitle: "product3",
    img: product3,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "stoppedAds4",
    productTitle: "product4",
    img: product4,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
];
export const productsForYou: IProduct[] = [
  {
    id: "forYou1",
    productTitle: "product1",
    img: product1,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "forYou2",
    productTitle: "product2",
    img: product2,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "forYou3",
    productTitle: "product3",
    img: product3,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "forYou4",
    productTitle: "product4",
    img: product4,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
];
export const similarProducts: IProduct[] = [
  {
    id: "similarProducts1",
    productTitle: "product1",
    img: product1,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "similarProducts2",
    productTitle: "product2",
    img: product2,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "similarProducts3",
    productTitle: "product3",
    img: product3,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
  {
    id: "similarProducts4",
    productTitle: "product4",
    img: product4,
    price: "3 900 000",
    oldPrice: "4 700 000",
    date: "14 ноя. – 21 дек.",
    location: "tashkent",
    discountAmount: 50,
    promoCode: "START50",
    discount: true,
    isTop: true,
    userName: "Macbro",
    avatar: avatar,
    viewers: "124",
    memory: "memory",
    memoryType: { "64gb": "64gb", "128gb": "128gb", "256gb": "256gb" },
    slot: "dual",
    productColor: "productColor",
    discountDeadline: "2025-12-21",
    complaint: "complaint",
    color: { black: "black", green: "green", blue: "blue", grey: "grey" },
    adminDesc: "adminDesc",
    follow: "follow",
    phone: "+998901234567",
    productDetail: "productDetail",
    detailInfo: "detailInfo",
    characteristics: "characteristics",
    comments: "comments",
    characteristicsType: [
      {
        id: 1,
        key: "ISBNKey",
        value: "ISBNValue",
      },
      {
        id: 2,
        key: "authorKey",
        value: "authorValue",
      },
      {
        id: 3,
        key: "languageKey",
        value: "languageValue",
      },
      {
        id: 4,
        key: "scriptKey",
        value: "scriptValue",
      },
      {
        id: 5,
        key: "pageCountKey",
        value: "pageCountValue",
      },
      {
        id: 6,
        key: "publisherKey",
        value: "publisherValue",
      },
      {
        id: 7,
        key: "coverTypeKey",
        value: "coverTypeValue",
      },
      {
        id: 8,
        key: "paperFormatKey",
        value: "paperFormatValue",
      },
      {
        id: 9,
        key: "publishYearKey",
        value: "publishYearValue",
      },
    ],
  },
];
